version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bankappdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=6563
    networks:
      - bankapp-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=6563
      - MYSQL_DATABASE=bankappdb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bankapp-network

volumes:
  mysql_data:

networks:
  bankapp-network: