services:
  - type: web
    name: bankapp
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /login
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
